name: work-1
on:
  push:
    branches:
      - main
jobs:
  hi1:
    runs-on: ubuntu-latest
    steps:
      - name: sayHi
        run: echo "Hi"
      - name: sayMyName
        run: echo "${{ github.actor }}"
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: sayHello
        run: echo "Hello"
  java1:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java HelloWorldApp.java
