name: work-1
on:
  push:
    branches:
      - main
jobs:
  hi1:
    runs-on: ubuntu-latest
    steps:
      - name: sayHi
        run: echo "Hi"
      - name: sayMyName
        run: echo "${{ github.actor }}"
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: sayHello
        run: echo "Hello"
